version: "3.9"

volumes:
  db:

services:

  web:
    build: .
    volumes:
      - "./:/app/"
      - "./log:/app/log"
    environment:
      - VIRTUAL_PORT=3000
      - VIRTUAL_HOST=scibot.test
    ports:
      - "3000:3000"
    command: bash -c "rails s -b 0.0.0.0"
    depends_on:
      db:
        condition: service_started

  db:
    image: postgres:14
    env_file:
      - .env
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USER}
      - VIRTUAL_PORT=5432
      - VIRTUAL_HOST=db.scibot.test
    volumes:
      - db:/var/lib/postgresql/data
