version: "3.9"

volumes:
  db:

services:

  web:
    build:
      target: web
      context: .
    volumes:
      - "./:/app/"
      - "./log:/app/log"
    environment:
      - VIRTUAL_PORT=3000
      - VIRTUAL_HOST=scibot.test
    env_file:
      - .env
      - .env.development
    ports:
      - "3000:3000"
    command: bash -c "rails s -b 0.0.0.0"
    depends_on:
      db:
        condition: service_started

  db:
    image: postgres:14
    env_file:
      - .env
    environment:
      - POSTGRES_DB=${DATABASE_NAME}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_USER=${DATABASE_USER}
    volumes:
      - db:/var/lib/postgresql/data
